### ISSUE TITLE
RuleUnitController가 RuleUnit의 플로우차트에서 /u 등 유니코드를 잘못 읽어 발생하는 문제

### ISSUE THREAD

**Issue by jooinjang** [KU-HIAI/tomok#16]
플로우차트에서 수식을 위해 사용하는 LaTeX 문법 /upsilon 등을 읽을 때, Unicode error가 발생하는 문제

![image](https://github.com/KU-HIAI/tomok/assets/99159690/d3e5367c-4da4-4f37-9c01-84a77a2b5dd0)

**Comment by jooinjang** [comment]
line 60 문자열 정보

https://latex.codecogs.com/svg.image?\upsilon&space;_u=\frac{\beta&space;V_u}{zb}

**Comment by taeminlee** [comment]
/mnt/md0/persuade/tomok/tomok_assets/raw_files/ipynbs/KDS241421_04010205_02.ipynb

변환 전 작성 파일(KDS241421_04010205_02.ipynb)에서도 같은 오류가 발생 

```
Cell In[1], [line 53](vscode-notebook-cell:?execution_count=1&line=53)
    """
       ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 1252-1253: truncated \uXXXX escape
```
