### ISSUE TITLE
colab 실행 오류

### ISSUE THREAD

**Issue by taeminlee** [KU-HIAI/tomok#4]
![image](https://github.com/KU-HIAI/tomok/assets/237049/1f548a15-5132-4a40-8ef7-023a39aaac4c)

**Comment by taeminlee** [comment]
python import할 때 사용되는 sys.path에 '/content' 만 포함되어 있음.
tomok 라이브러리는 /content/tomok/tomok에 있어서 불러오기가 안됨

**Comment by taeminlee** [comment]
![image](https://github.com/KU-HIAI/tomok/assets/237049/f7aeb92f-ff39-449d-875b-64412509a687)

로컬 실행 확인

**Comment by taeminlee** [comment]
![image](https://github.com/KU-HIAI/tomok/assets/237049/854c50e2-a205-44a2-9e75-0e0f7b93c032)

colab 실행 확인

**Comment by taeminlee** [comment]
다만, 임시 방편에 지나지 않음.
장기적으로는 sys.path에 tomok 프로젝트를 추가하거나, git clone이 아닌 pip로 설치하도록 해야함

**Comment by jooinjang** [comment]
예예 pip으로 설치시키는게 백번 맞는거같습니다...

**Comment by jooinjang** [comment]
가능하면 작업자들이 ipynb(코랩기반)말고 python IDE에서 .py로 RuleIFC에 바로 쓸 수 있게 짜주는게 베스트인데 그것도 일단 제가 가이드라인을 만들어야해서..ㅠㅠㅠㅠㅠㅠㅠ 산넘어산이군요
